### PR TITLE
Added image_prompt feature to text2img

### PR DESCRIPTION
**Pull request by bsormagec**
I added a new endpoint to the Ability IP module that features text2img prompts. Unfortunately, I couldn't add any examples today because it's New Year's Eve, but I wanted to release this update before 2024. This might be the last release before that year. Anyway, Happy New Year! 🎄 @konieshadow @mrhan1993

### CODE REVIEW

**Comment by bsormagec** [comment]
@mrhan1993 if you are around can you check and merge it ?

**Comment by mrhan1993** [comment]
sorry so late, but i am not sure is this a repeat。

```python
params = {
  "prompt": "",
  "negative_prompt": "",
  "style_selections": [
    "Fooocus V2",
    "Fooocus Enhance",
    "Fooocus Sharp"
  ],
  "performance_selection": "Speed",
  "aspect_ratios_selection": "1152*896",
  "image_number": 1,
  "image_seed": -1,
  "sharpness": 2,
  "guidance_scale": 4,
  "base_model_name": "juggernautXL_version6Rundiffusion.safetensors",
  "refiner_model_name": "None",
  "refiner_switch": 0.5,
  "loras": [
    {
      "model_name": "sd_xl_offset_example-lora_1.0.safetensors",
      "weight": 0.1
    }
  ],
  "advanced_params": {
    "adaptive_cfg": 7,
    "adm_scaler_end": 0.3,
    "adm_scaler_negative": 0.8,
    "adm_scaler_positive": 1.5,
    "canny_high_threshold": 128,
    "canny_low_threshold": 64,
    "controlnet_softness": 0.25,
    "debugging_cn_preprocessor": False,
    "debugging_inpaint_preprocessor": False,
    "disable_preview": False,
    "freeu_b1": 1.01,
    "freeu_b2": 1.02,
    "freeu_enabled": False,
    "freeu_s1": 0.99,
    "freeu_s2": 0.95,
    "inpaint_disable_initial_latent": False,
    "inpaint_engine": "v1",
    "inpaint_respective_field": 1,
    "inpaint_strength": 1,
    "mixing_image_prompt_and_inpaint": False,
    "mixing_image_prompt_and_vary_upscale": False,
    "overwrite_height": -1,
    "overwrite_step": -1,
    "overwrite_switch": -1,
    "overwrite_upscale_strength": -1,
    "overwrite_vary_strength": -1,
    "overwrite_width": -1,
    "refiner_swap_method": "joint",
    "sampler_name": "dpmpp_2m_sde_gpu",
    "scheduler_name": "karras",
    "skipping_cn_preprocessor": False
  },
  "require_base64": False,
  "async_process": False,
  "webhook_url": "",
  "input_image": "",
  "input_mask": "",
  "inpaint_additional_prompt": "",
  "outpaint_selections": [],
  "outpaint_distance_left": -1,
  "outpaint_distance_right": -1,
  "outpaint_distance_top": -1,
  "outpaint_distance_bottom": -1,
  "image_prompts": [
    {
      "cn_img": "string",
      "cn_stop": 0,
      "cn_weight": 0,
      "cn_type": "ImagePrompt"
    },
    {
      "cn_img": "string",
      "cn_stop": 0,
      "cn_weight": 0,
      "cn_type": "ImagePrompt"
    }
  ]
}

import requests
import json
import base64

image1 = open('.\\examples\\imgs\\bear.jpg', 'rb').read()
image2 = open('.\\examples\\imgs\\s.jpg', 'rb').read()

img_prompt = [
    {
        "cn_img": base64.b64encode(image1).decode('utf-8'),
        "cn_stop": 0.6,
        "cn_weight": 0.6,
        "cn_type": "ImagePrompt"
    },{
        "cn_img": base64.b64encode(image2).decode('utf-8'),
        "cn_stop": 0.6,
        "cn_weight": 0.6,
        "cn_type": "ImagePrompt"
    }
]

def image_prompt(img_prompt: list, params: dict) -> dict:
    """
    Image Prompt
    """
    params["input_image"] = base64.b64encode(image1).decode('utf-8')
    params["prompt"] = "cat"
    params["image_prompts"] = img_prompt
    data = json.dumps(params)
    response = requests.post(url="http://127.0.0.1:8888/v2/generation/image-prompt",
                        data=data,
                        timeout=300)
    return response.json()

r = image_prompt(img_prompt, params)
```
here is the output

7bb37b17-c27d-4660-beb4-2fe2d43eb1cc

**Comment by bsormagec** [comment]
This is not exactly what I am doing because you are using inpainting with an image. With my endpoint, I am generating text2img and applying the generated image at the same time as ImagePrompt. @mrhan1993

**Comment by mrhan1993** [comment]
ok , i think i understand.

**Pull request merged**
